In [2]:
import os, sys, inspect
# sys.path.append('../..')

import pandas as pd
from pathlib import Path
import glob as glob
import os
import numpy as np
import re
import json
from datetime import datetime, timedelta, date
from connection import SCORE_DB_CONN, ANALYTICS_DB_CONN
from avay_bq import AvayBQServiceAcc
from da_utils.client.bigquery_client import BigqueryClient
from da_utils.client.google_sheets_client import GoogleSheetsClient
from da_utils.repository.google_sheets.google_sheets_repository import GoogleSheetsService
from da_utils.repository.bigquery.bigquery_repository import BigqueryService



pd.set_option("display.max_row", 100)

In [10]:
adc_path = Path('/home/linhnguyen/.config/gcloud/application_default_credentials.json')
avay_bq_acc = AvayBQServiceAcc()
bq_client = BigqueryClient(billing_project_id='prj-ts-p-analytic-8057', adc_file_path=adc_path)
bq_repo = BigqueryService(bq_client)

client = GoogleSheetsClient()
repo = GoogleSheetsService(client)
workbook = repo.open_spreadsheet("1U9QDxArDL7MxYMs2H2-xVRbwfApTEJbahaKZoN1lY9s")
workbook2 = repo.open_spreadsheet("19D57H_pstFiff_dt_F5ewjqGnAOkSnE1Q9m2lFJCFsg")

In [11]:
lead_phone_infos = avay_bq_acc.client.query(f"""
with rangedate as (
    select
date('2023-01-01') as sdate,
date('2023-07-31') as edate
)
,qualified as(
    select 
        lead_id
        ,case when lead_source in ('Accesstrade', 'Vaycucde') then 'Accesstrade'
            when lead_source_group = 'Facebook' then 'Facebook'
            when lead_source_group = 'Google ads' then 'Google'
            when lead_source in ('Viettel Pay', 'Viettel Pay Pro') then 'VTP'
        else 'Others' end as lead_source
        ,case when telco_code in('viettel') then telco_code else 'others' end as telco_code
        ,loan_date
        ,bank_name
        ,offer_code
        ,round(unit_cost) as cost
    from `avay-a9925.datamart.avay_compound`, rangedate
    where loan_date between sdate and edate
        and loan_status in ('accepted', 'checking-lead')
)

select * from qualified
        """).result().to_arrow().to_pandas()

lead_phone_infos.fillna(0).head()
lead_phone_infos = lead_phone_infos.fillna(0)

In [12]:
disbursed1 = avay_bq_acc.client.query(f"""
with rangedate as (
    select
date('2023-01-01') as sdate,
date('2023-07-31') as edate
),
disbursed as
(
    select 
        lead_id
        ,case when disbursed_date = '2000-01-01' then loan_date else disbursed_date end as disbursed_date
        ,commission as gross_revenue
    from `avay-a9925.datamart.avay_compound`, rangedate
    where loan_date between sdate and edate and disbursed_date is not null

)

select * from disbursed
        """).result().to_arrow().to_pandas()

disbursed1.fillna(0).head()
disbursed1 = disbursed1.fillna(0)

In [13]:
disbursed2 = bq_repo.get_data_from_query_into_pandas(f"""
with rangedate as (
    select
date('2023-01-01') as sdate,
date('2023-07-31') as edate
),
disbursed as
(select 
  lead_id, 
  case when disbursed_date = '2000-01-01' then batch_date else disbursed_date end as disbursed_date,
  commission as gross_revenue
from `prj-ts-p-analytic-8057.da.disbursals`, rangedate
where true
and batch_date between sdate and edate
)

select * from disbursed
        """)

disbursed2.fillna(0).head()
disbursed2 = disbursed2.fillna(0)

In [17]:
df00 = pd.read_excel('/home/linhnguyen/TS 28.6.xlsx', sheet_name = 'DLT4')
df00 = df00[['ID đối tác','App Code']]
df00 = df00.rename(columns={"ID đối tác": "lead_id", "App Code": "app_code"})
df00 = df00.fillna(0)
df00['lead_id'] = df00['lead_id'].astype(int)

df01 = pd.read_excel('/home/linhnguyen/TS 28.6.xlsx', sheet_name = 'DLT5')
df01 = df01[['ID đối tác','App Code']]
df01 = df01.rename(columns={"ID đối tác": "lead_id", "App Code": "app_code"})
df01 = df01.fillna(0)
df01['lead_id'] = df01['lead_id'].astype(int)

df02 = pd.read_excel('/home/linhnguyen/TS 28.6.xlsx', sheet_name = 'DLT6')
df02 = df02[['ID đối tác','App Code']]
df02 = df02.rename(columns={"ID đối tác": "lead_id", "App Code": "app_code"})
df02 = df02.fillna(0)
df02['lead_id'] = df02['lead_id'].astype(int)

df1 = pd.concat([df02, df01, df00])

df2 = pd.read_excel('/home/linhnguyen/TS 28.6.xlsx', sheet_name = 'SỐ CASE LOAN')
df2 = df2[{'Mã hồ sơ', 'Sản phẩm', 'Số tiền được duyệt', 'Ngày giải ngân'}]
df2 = df2.rename(columns={"Sản phẩm": "product", "Mã hồ sơ": "app_code", "Số tiền được duyệt":"loan_amount", "Ngày giải ngân":"disbursed_date"})
df2['disbursed_date'] = pd.to_datetime(df2['disbursed_date'], format='%d/%m/%Y').dt.normalize()
fee_rate = pd.DataFrame(
    [
        {"product": "TRS01", "fee_rate": 0.055},
        {"product": "TRS02", "fee_rate": 0.06},
        {"product": "TSL01", "fee_rate": 0.055},
    ]
) 
df = df1.merge(df2, how = 'left').merge(fee_rate).assign(gross_revenue = lambda x: x.loan_amount * x.fee_rate)
disbursed3 = df[['lead_id','disbursed_date','loan_amount','gross_revenue']]
disbursed3['lead_id'] = disbursed3['lead_id'].astype(int)
disbursed3

/home/linhnguyen/.venv/lib/python3.9/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")
/tmp/ipykernel_270608/73039800.py:22: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  df2 = df2[{'Mã hồ sơ', 'Sản phẩm', 'Số tiền được duyệt', 'Ngày giải ngân'}]
/tmp/ipykernel_270608/73039800.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  disbursed3['lead_id'] = disbursed3['lead_id'].astype(int)

      lead_id disbursed_date  loan_amount  gross_revenue
0    14205128     2023-06-28   15000000.0       900000.0
1    14202845     2023-06-27   15000000.0       900000.0
2    14198341     2023-06-28   30000000.0      1800000.0
3    14192242     2023-06-24   30000000.0      1800000.0
4    14185284     2023-06-22   10000000.0       600000.0
..        ...            ...          ...            ...
421  13923634     2023-04-07   30000000.0      1650000.0
422  13911137     2023-04-05   20000000.0      1100000.0
423  13906215     2023-04-06   15000000.0       825000.0
424  13901330     2023-04-15   10000000.0       550000.0
425  13900203     2023-04-13   10000000.0       550000.0

[426 rows x 4 columns]

In [16]:
ceoo = pd.read_csv('/home/linhnguyen/CEOO_daily.csv')
ceoo = ceoo[~ceoo['DISBURSED_DATE'].isnull()]
ceoo.rename(columns = {'DISBURSED_DATE': 'disbursed_date', 'APPROVED_LOAN_AMOUNT': 'loan_amount', 'ts_lead_id': 'lead_id'}, inplace = True)
ceoo['loan_amount'] = ceoo['loan_amount'].replace(',', '').astype(float)
ceoo['gross_revenue'] = ceoo['loan_amount']*0.03
ceoo = ceoo[['lead_id', 'disbursed_date', 'loan_amount', 'gross_revenue']]
ceoo

          lead_id disbursed_date  loan_amount  gross_revenue
1081     13968672     2023-04-18   13574000.0       407220.0
1082     13968672     2023-04-18   13574000.0       407220.0
1083     13968672     2023-04-18   13574000.0       407220.0
1084     13968672     2023-04-18   13574000.0       407220.0
1085     13968672     2023-04-18   13574000.0       407220.0
...           ...            ...          ...            ...
2096536  13579667     2023-02-02   10000000.0       300000.0
2096588  13579326     2023-02-10   10000000.0       300000.0
2096592  13583094     2023-02-06   10000000.0       300000.0
2096650  13589331     2023-02-09   10000000.0       300000.0
2096739  13580693     2023-02-06   16125000.0       483750.0

[60520 rows x 4 columns]

In [18]:
# disbursed = disbursed1.combine_first(disbursed2).combine_first(disbursed3)

disbursed = pd.concat([disbursed1, disbursed2, disbursed3, ceoo])
disbursed = disbursed.drop_duplicates(subset=['lead_id'])
disbursed = disbursed.fillna(0)
disbursed['gross_revenue'] = disbursed['gross_revenue'].astype('float')
disbursed[disbursed['lead_id']==13733718]

       lead_id disbursed_date  gross_revenue  loan_amount
9720  13733718     2023-03-01       825000.0          0.0

In [19]:
leads_with_disbursement = lead_phone_infos.merge(disbursed, how = 'left').assign(
    lead_sent_day=lambda x: x.loan_date.astype(str).str[8:10].astype(int),
    lead_sent_month=lambda x: x.loan_date.astype(str).str[0:7],
    loan_sent_month=lambda x: x.disbursed_date.astype(str).str[0:7],)


leads_with_disbursement["loan_in_month"] = np.where((leads_with_disbursement["disbursed_date"].notnull())&(leads_with_disbursement["loan_sent_month"] == leads_with_disbursement["lead_sent_month"]) ,1,0)
leads_with_disbursement["loan_next_month"] = np.where((leads_with_disbursement["disbursed_date"].notnull())&(leads_with_disbursement["loan_sent_month"] != leads_with_disbursement["lead_sent_month"]) ,1,0)

leads_with_disbursement["commission_in_month"] = np.where((leads_with_disbursement["disbursed_date"].notnull())&(leads_with_disbursement["loan_sent_month"] == leads_with_disbursement["lead_sent_month"]) ,leads_with_disbursement["gross_revenue"],0)
leads_with_disbursement["com_next_month"] = np.where((leads_with_disbursement["disbursed_date"].notnull())&(leads_with_disbursement["loan_sent_month"] != leads_with_disbursement["lead_sent_month"]) ,leads_with_disbursement["gross_revenue"],0)
leads_with_disbursement= leads_with_disbursement.fillna(0)
leads_with_disbursement

,lead_id,lead_source,telco_code,loan_date,bank_name,offer_code,cost,disbursed_date,gross_revenue,loan_amount,lead_sent_day,lead_sent_month,loan_sent_month,loan_in_month,loan_next_month,commission_in_month,com_next_month
0,14017452,Others,others,2023-05-01,Lotte Finance,LOTTE00,0,0,0.0,0.0,1,2023-05,nan,0,0,0.0,0.0
1,14015980,Others,others,2023-05-01,Lotte Finance,LOTTE00,0,0,0.0,0.0,1,2023-05,nan,0,0,0.0,0.0
2,14016870,Others,others,2023-05-01,Lotte Finance,LOTTE00,0,0,0.0,0.0,1,2023-05,nan,0,0,0.0,0.0
3,14015967,VTP,others,2023-05-01,Lotte Finance,LOTTE00,0,0,0.0,0.0,1,2023-05,nan,0,0,0.0,0.0
4,14016240,Others,others,2023-05-01,Lotte Finance,LOTTE00,0,0,0.0,0.0,1,2023-05,nan,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212865,14009051,VTP,viettel,2023-04-28,FE Credit,FECEOO_VT_LOW,0,0,0.0,0.0,28,2023-04,nan,0,0,0.0,0.0
212866,13840706,VTP,viettel,2023-03-20,FE Credit,FECEOO_VT_LOW,0,0,0.0,0.0,20,2023-03,nan,0,0,0.0,0.0
212867,13887147,VTP,viettel,2023-03-29,FE Credit,FECEOO_VT_LOW,0,2023-04-02,300000.0,0.0,29,2023-03,2023-04,0,1,0.0,300000.0
212868,13683541,VTP,viettel,2023-02-18,FE Credit,FECEOO_VT_LOW,0,0,0.0,0.0,18,2023-02,nan,0,0,0.0,0.0
212869,13577547,VTP,viettel,2023-01-16,FE Credit,FECEOO_VT_LOW,0,0,0.0,0.0,16,2023-01,nan,0,0,0.0,0.0

In [26]:
# check = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,3,1))
#                         &(leads_with_disbursement['loan_date']<date(2023,4,1))
#                         &(leads_with_disbursement['offer_code'] == 'FECEOO_NONVT')
#                         &(leads_with_disbursement['lead_source'] == 'Accesstrade')
#                         &(leads_with_disbursement["loan_in_month"] ==1)]

# workbookcheck = repo.open_spreadsheet_by_key("17UrX637sXSfXDgoTr208Lf6-jdDdMd4Nc9vNL_EX8l4")
# repo.write_df_to_sheet(workbookcheck.worksheet("Sheet1"),check, starting_cell = 'K1')

In [49]:
output1 = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,3,1))&(leads_with_disbursement['loan_date']<date(2023,4,1))].groupby([ "lead_source", "telco_code", "bank_name", "offer_code"]).agg({"lead_id":"count", "cost":"sum", "loan_in_month":"sum", "commission_in_month":"sum", "loan_next_month":"sum", "com_next_month":"sum"}).reset_index()

repo.write_df_to_sheet(workbook2.worksheet("03-2023"),output1, starting_cell = 'W1')

In [50]:
output2 = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,4,1))&(leads_with_disbursement['loan_date']<date(2023,5,1))].groupby([ "lead_source", "telco_code", "bank_name", "offer_code"]).agg({"lead_id":"count", "cost":"sum", "loan_in_month":"sum", "commission_in_month":"sum", "loan_next_month":"sum", "com_next_month":"sum"}).reset_index()

repo.write_df_to_sheet(workbook2.worksheet("04-2023"),output2, starting_cell = 'W1')

In [23]:
output3 = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,5,1))&(leads_with_disbursement['loan_date']<date(2023,6,1))].groupby([ "lead_source", "telco_code", "bank_name", "offer_code"]).agg({"lead_id":"count", "cost":"sum", "loan_in_month":"sum", "commission_in_month":"sum", "loan_next_month":"sum", "com_next_month":"sum"}).reset_index()

repo.write_df_to_sheet(workbook2.worksheet("05-2023"),output3, starting_cell = 'W1')

In [25]:
output4 = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,6,1))&(leads_with_disbursement['loan_date']<date(2023,6,30))].groupby([ "lead_source", "telco_code", "bank_name", "offer_code"]).agg({"lead_id":"count", "cost":"sum", "loan_in_month":"sum", "commission_in_month":"sum", "loan_next_month":"sum", "com_next_month":"sum"}).reset_index()

repo.write_df_to_sheet(workbook2.worksheet("06-2023"),output4, starting_cell = 'W1')

KeyboardInterrupt:

In [22]:

output4 = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,7,1)) & (leads_with_disbursement['loan_date']<= date(2023,7,10))].groupby(["telco_code", "bank_name", "offer_code", "lead_source"]).agg({"lead_id":"count"}).reset_index()
repo.write_df_to_sheet(workbook2.worksheet("Method"),output4, starting_cell = 'W1')

output4 = leads_with_disbursement[(leads_with_disbursement['loan_date']>= date(2023,7,4)) & (leads_with_disbursement['loan_date']<= date(2023,7,10))].groupby(["telco_code", "bank_name", "offer_code", "lead_source"]).agg({"lead_id":"count"}).reset_index()
repo.write_df_to_sheet(workbook2.worksheet("Method"),output4, starting_cell = 'W51')